apiVersion: apps/v1
kind: Deployment
metadata:
  name: cataloguing
  namespace: utility
  labels:
    app: cataloguing
    env: charite
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cataloguing
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: cataloguing
        env: charite
    spec:
      containers:
        - name: cataloguing
          image: 10.32.42.225:5000/cataloguing:<VERSION>
          ports:
            - containerPort: 5064
          env:
          - name: env
            value: "charite"
          readinessProbe:
            tcpSocket:
              port: 5064
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "500m"
      nodeSelector:
        namespace: utility
---
apiVersion: v1
kind: Service
metadata:
  name: cataloguing
  namespace: utility
  labels:
    app: cataloguing
spec:
  ports:
  - name: http
    port: 5064
    targetPort: 5064
    nodeport:
  selector:
    app: cataloguing
  type: ClusterIP